function f = fixtures()
f.healthy = struct("t",1,"solver","ode15s","relTol","1e-6","absTol","1e-8", ...
    "residualNorm",0.02,"energy",2.1,"energyTrend","flat","maxAbsState",2.2, ...
    "stiffnessHint",50,"nWarnings",0,"warnings","","lastAction","continue", ...
    "notes","van der Pol after solver switch");

f.stiffOnOde45 = struct("t",0.4,"solver","ode45","relTol","1e-3","absTol","1e-6", ...
    "residualNorm",80,"energy",9.5,"energyTrend","rising_fast","maxAbsState",8, ...
    "stiffnessHint",2e4,"nWarnings",3,"warnings","Step size too small; tolerance not met", ...
    "lastAction","continue","notes","mu=1000 started with ode45");

f.blowup = struct("t",3.2,"solver","ode45","relTol","1e-3","absTol","1e-6", ...
    "residualNorm",1e12,"energy",1e14,"energyTrend","exploding","maxAbsState",1e8, ...
    "stiffnessHint",1e9,"nWarnings",6,"warnings","NaN detected in derivative", ...
    "lastAction","tighten","notes","injected blow-up");
end
