function questions = jevQuestions()
questions.action = struct( ...
    "type", "choice", ...
    "instructions", "Choose the next supervisor action for this numerical integration. Prefer the least invasive action that keeps the trajectory physically plausible and numerically stable.", ...
    "criteria", struct( ...
        "continue", "Integration is healthy enough to keep current solver and tolerances.", ...
        "tighten", "Reduce step size or tighten RelTol/AbsTol. Do not change solver family.", ...
        "switch_solver", "Current solver is a poor fit (e.g. nonstiff solver on a stiff system). Switch solver family.", ...
        "abort", "Continuing is unsafe or meaningless. Stop now."));

questions.health = struct( ...
    "type", "score", ...
    "instructions", "Score numerical health of this run. 0 is stable and well-scaled. 3 is diverging or unusable.", ...
    "criteria", {{ ...
        "stable: residuals small, energy bounded, no repeated step failures", ...
        "noisy: usable but tolerances or steps are strained", ...
        "stiff_or_poorly_scaled: likely wrong solver or scales", ...
        "diverging_or_unusable: blow-up, NaN risk, or physically implausible"}});

questions.physically_plausible = struct( ...
    "type", "noul", ...
    "instructions", "Is the current trajectory still physically or numerically plausible given notes, energy trend, and warnings?");
end
